eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8100

spring:
  application:
    name: student-service
  datasource:
    driver-class-name: org.h2.Driver
    password:
    platform: h2
    url: jdbc:h2:mem:restdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect