eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost

server:
  port: 8761
