eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8150

spring:
  application:
    name: student-view
  servlet:
    multipart:
      enabled: true  
